### ISSUE TITLE
Environment example on main page fails in Node 0.12.3

### ISSUE THREAD

**Issue by fasiha** [adambom/parallel.js#104]
The Fibonacci examples run fine:
```js
    var p = new Parallel([40, 41, 42]),
        log = function () { console.log(arguments); };
    function fib(n) {
      return n < 2 ? 1 : fib(n - 1) + fib(n - 2);
    };
    p.map(fib).then(log);
```
produces `> { '0': [ 165580141, 267914296, 433494437 ] }` eventually.

However, 
```js
var p = new Parallel([1, 2, 3], {
  env: {
    a: 10
  }
});
p.map(function (d) {
  return d * global.env.a;
}).then(log);
```
results in an error, because `global.env` is `undefined`:
```
> undefined:2
return d * global.env.a;
                     ^
TypeError: Cannot read property 'a' of undefined
    at eval (eval at <anonymous> (/path/node_modules/paralleljs/lib/eval.js:5:24), <anonymous>:2:22)
    at process.eval (eval at <anonymous> (/path/node_modules/paralleljs/lib/eval.js:5:24), <anonymous>:3:3)
    at process.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
undefined:2
return d * global.env.a;
                     ^
TypeError: Cannot read property 'a' of undefined
    at eval (eval at <anonymous> (/path/node_modules/paralleljs/lib/eval.js:5:24), <anonymous>:2:22)
    at process.eval (eval at <anonymous> (/path/node_modules/paralleljs/lib/eval.js:5:24), <anonymous>:3:3)
    at process.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```
Just updated Node to 0.12.3 on Mavericks.

**Comment by Sebmaster** [comment]
See #101.
