### ISSUE TITLE
node.js: setting up env do not work

### ISSUE THREAD

**Issue by syzer** [adambom/parallel.js#89]
```javascript
'use strict';
var _ = require('lodash');
var Parallel = require('paralleljs');
console.log(_.name);
console.time('time');

// Create a job
var p = new Parallel(100000, {
    env: {
        a: 10
    },
    envNamespace: 'parallel'
});

// Spawn a remote job (we'll see more on how to use then later)
var slowSquare = function (n) {
    console.log(global.parallel.a);
    //_.isString('true');
    var i = 0;
    while (++i < n * n) {}
    return i;
};

function yourCallback(data) {
    console.log(data);
    console.timeEnd('time');
}

// Spawn our slow function
p.spawn(slowSquare).then(yourCallback);

```

*throws:*
```
TypeError: Cannot read property 'a' of undefined
    at eval (eval at <anonymous> (C:\xampp\htdocs\testJS\nodeInAction\node_modules\paralleljs\lib\eval.js:5:24), <anonymous>:2:32)
    at process.eval (eval at <anonymous> (C:\xampp\htdocs\testJS\nodeInAction\node_modules\paralleljs\lib\eval.js:5:24), <anonymous>:7:3)
    at process.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
```

**Comment by 1aurabrown** [comment]
i'm experiencing this as well!

**Comment by maxvodo** [comment]
Seems to this repository available newer version of Parallel, than npm. Because I saw code for provide "global object" feature for "node" workers.

**Comment by Sebmaster** [comment]
Yes, this is due to the fact @adambom is MIA again and I can't update the npm package. If you need env, you'll have the add a dependency to the github repo.
